; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = teensy
board = teensy40
framework = arduino
lib_deps =
    paulstoffregen/Encoder@^1.4.4
    paulstoffregen/TimerOne@^1.1

[env:teensy_KF_accel]
build_src_filter = +<teensy_KF_accel/>

[env:teensy_furata_encoder]
build_src_filter = +<teensy_KF_accel/>

[env:read_furata_encoder]
build_src_filter = +<read_furata_encoder/>